apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eggcatcher
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   # clean up resources on app delete
spec:
  project: default

  source:
    repoURL: https://github.com/PakTechLimited/gitops-eggcatcher
    targetRevision: HEAD
    path: apps/eggcatcher
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: eggcatcher

  syncPolicy:
    automated:
      prune: true      # delete resources removed from Git
      selfHeal: true   # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=false   # namespace already created by Terraform
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
